const fs = require("fs");
const path = require("path");

const root = process.cwd();
const files = fs.readdirSync(root);

function detectLanguage() {
  if (files.includes("package.json")) return "JavaScript / TypeScript";
  if (files.includes("requirements.txt") || files.includes("pyproject.toml")) return "Python";
  if (files.includes("pom.xml") || files.includes("build.gradle")) return "Java";
  if (files.includes("go.mod")) return "Go";
  if (files.includes("Cargo.toml")) return "Rust";
  return "Unknown / Multi-language";
}

function installCmd(lang) {
  return {
    "JavaScript / TypeScript": "npm install",
    "Python": "pip install -r requirements.txt",
    "Java": "mvn install",
    "Go": "go mod tidy",
    "Rust": "cargo build"
  }[lang] || "See documentation";
}

function runCmd(lang) {
  return {
    "JavaScript / TypeScript": "npm start",
    "Python": "python main.py",
    "Java": "mvn spring-boot:run",
    "Go": "go run .",
    "Rust": "cargo run"
  }[lang] || "See documentation";
}

function tree(dir, depth = 0) {
  if (depth > 2) return "";
  return fs.readdirSync(dir, { withFileTypes: true })
    .filter(d => !["node_modules", ".git"].includes(d.name))
    .map(d => {
      const pad = "  ".repeat(depth);
      if (d.isDirectory()) {
        return `${pad}- 📂 ${d.name}\n${tree(path.join(dir, d.name), depth + 1)}`;
      }
      return `${pad}- 📄 ${d.name}\n`;
    }).join("");
}

const lang = detectLanguage();

const readme = `
# ${path.basename(root)}

## 📌 Overview
This is a **${lang}** project with automated documentation.

## ✨ Features
- Language-agnostic README generation
- Runs automatically on every push
- Clean and professional structure

## 🛠 Installation
\`\`\`bash
${installCmd(lang)}
\`\`\`

## ▶️ Usage
\`\`\`bash
${runCmd(lang)}
\`\`\`

## 🗂 Project Structure
\`\`\`
${tree(root)}
\`\`\`

## 📄 License
MIT

---
_Auto-generated by GitHub Actions._
`;

fs.writeFileSync("README.md", readme.trim());
console.log("README generated");
